### ISSUE TITLE
Connecting with Node Foundation Marketing

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#100]
We _need_ to get in touch with the Node Foundation marketing people to start working together and ironing out our content flow, as well as obtain official credentials for Node.js social account holdings. The only person I know who may know who to contact is @misterdjules, as he talked about them in the Website WG meeting today.

If anybody knows who we can get in touch with to start a dialogue, the WG will be very thankful.

**Comment by rvagg** [comment]
I don't think there are any foundation marketing people beyond the folks at Linux Foundation.

All "we" currently have is a basic board made up of a representative of each of the Platinum members and a rep from the TSC (sort of, that's complicated). By early next month they will be joined by one representative each from the Gold and Silver members of the foundation and then proceed to hiring an executive director who will be like the day-to-day executive person managing the business activities of the foundation with the board there to approve, critique or reject their proposals and activities.

_Our_ goal as a community should be to own as much of this as possible rather than leaning too much on the board, the ED or any other party in there. If we need resources then they should filter from our working groups upward. The ED may appoint some kind of marketing resources to help with the really complicated (and expensive) parts of marketing and social media management and whatnot but IMO as much as possible it should be community driven.

My suggestion to the Evangelism WG is to start considering a pivot away from pure io.js evangelism to Node evangelism which encompasses both projects and the foundation. You're going to have to decide what level of comfort you have there and what the breath of the responsibilities you want to take on board are but _please_ consider yourselves as the drivers of the efforts here rather than trying to slot in under some other formal structure. The more this is community-driven the better it will be for all of us, including the foundation. The ideal from my perspective would be for this group to be running evangelism and requesting and even coordinating paid resources from the foundation via the ED, with the ED serving at the pleasure of each of the working groups and doing their bidding—with a reasonable amount of coordination as we would expect from a facilitator rather than a "leader".

I'll ping the LF contacts I have and point them to this thread to see if they have any input to give.

**Comment by bnb** [comment]
@rvagg Thanks for the response. I completely agree that we should move to branding our output as Node instead of io.js. What do we need to do to get control of some of the social media assets (namely the Twitter account), and access to the official blog? 

I think it would be very, very, _very_ smart to publish our first Node.js Weekly Update tomorrow, in lieu of an io.js Weekly Update. Doing this the same week as the Linux Foundation announcement is a good way to ride off the current publicity.

The issue that content creation would occur in: https://github.com/nodejs/evangelism/issues/97

**Comment by rvagg** [comment]
@bnb love it!

Blog access will be back via the @nodejs/website group I believe because it's all in [here](https://github.com/joyent/node-website/tree/master/doc/blog).

Twitter access, who has access to `@official_iojs` at the moment? Is it shared amongst this whole group or a subset? My guess is that this is the same group that should be requesting creds for `@nodejs` and that's probably best done via email.

**Comment by bnb** [comment]
@rvagg Sweet, I just requested the node-website be moved to nodejs/nodejs.org, so if we get that done sometime tomorrow, we can have the blog post out ASAP. 

@mikeal, @julianduque, and a few other people have the official Twitter account creds - it's been made clear that as long as you're a contributor (not in the GitHub sense, in the community sense) to the Evangelism WG, you can request and gain access to the Twitter account. I've not asked as I was campaigning to get the actual @iojs twitter handle and/or waiting until we got the official Node handle. Who should we email for those creds?

**Comment by yosuke-furukawa** [comment]
I also completely agree the @rvagg's suggestion.

I have a permission to access twitter account (@official_iojs).

**Comment by rvagg** [comment]
Finding out who exactly it is that has the current creds, will let you know who to contact as soon as I know!

:seedling:

**Comment by snostorm** [comment]
@bnb the website WG has permissions around https://github.com/joyent/node-website already, even though it isn't sitting in the `nodejs` organization yet. So we're not technically blocked right now for being able to approve PRs and push to that repo.

@rvagg if I read your reply right it'll be this group taking on the general marketing/branding responsibilities? I want to make sure we have some good processes in place for developing brand resources and reusable standards. (And I'm sure we can get the ball rolling on this as a community, even if we eventually want to bring in some sponsored/paid resources for some future heavy lifting -- aka fancy future graphics.)

**Comment by rvagg** [comment]
As far as I understand there is nothing else in place that would prevent this group from being _the_ marketing group for the foundation (I could be missing something of course). The sooner you get on top of it and get properly organised for the role the greater likelihood that this will continue like this into the future with this group playing a strong role in directing the marketing resources of the foundation. The obviously has final approval of budget use but I don't imagine that being a problem if this group levels up to the task and is able to direct sensible expenditure through the ED.

I'll certainly be using any influence I may have to be pushing for community driven action throughout the foundation but we need people to step up to the task.

**Comment by mikeal** [comment]
Let me clarify a few things real quick.

The foundation spun up an ad-hock marketing group to handle the launch of the foundation. That had a few reps from members of the foundation along with the LF PR team. I was pulled in towards the end and have been talking to analysts and journalists at their request this week. I don't think this _exact_ team will meet again since the launch is pretty much out.

The membership agreements reference a "Marketing Committee" at the foundation which each member has a voice in. I recall that we did ratify the _ability_ to using spin up committees in the first board meeting but I don't think this was specifically spun up. I would expect it to get spun up and for them to start meeting over the next month or so.

That said, don't block anything you want to do waiting for this group to meet.

I'll try to figure out who has the credentials for the twitter account. Does anyone know of a good/secure way to share them?

**Comment by bnb** [comment]
@mikeal Re: sharing credentials securely: TweetDeck has a good interface for team accounts (I saw you were having problems with it - I'd be happy to work with you to get it working/understand how it works). 

There's also LastPass password sharing, where the password is shared between LastPass accounts' vaults, but the people who it is shared with cannot actually see it. LastPass automatically fills the login field, and then allows login. On the topic of LastPass security, they did not lose any of the highly-encrypted password data stored in vaults, and very little was compromised. I chose LastPass because they're the only ones with a solid encryption standard; the vast majority of other password managers lack their level of security, and it can be undoubtedly trusted.

**Comment by mikeal** [comment]
@bnb I'll check out LastPass. I don't want to do TweetDeck because I don't want to dictate which client we're using.

**Comment by bnb** [comment]
@mikeal I suggest just trying it out. There's also documentation here: https://helpdesk.lastpass.com/sharing/

**Comment by snostorm** [comment]
Sounds like there's a good opportunity for us (in the meantime) to figure out where to draw the lines between evangelism, marketing and website. We can get some foundational work in place so that by time a marketing committee spins up some of the leg work has been done and they have some resources to start with :)

**Comment by mikeal** [comment]
@snostorm love it :)

**Comment by bnb** [comment]
@snostorm How would you like to start that? I'm drawing a blank on what the first step would be in drawing those lines.

**Comment by bnb** [comment]
@mikeal any updates on `@nodejs` credentials on Twitter?

**Comment by mikeal** [comment]
I brought it up last Friday, the LF is going to follow up with Scott about it.
