### ISSUE TITLE
Social Media Management

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#119]
There's a discussion that we need to have about how we want to manage social media and if we want to continue taking responsibility for this long term or if we would prefer for marketing resources in the foundation to take this on.

Right now the social media resources are "under-managed." I used to respond to everything myself on official_iojs but haven't been able to in some time. That was a lot of work when I was doing it but it's much less than would be required for managing @nodejs.

So, I have two questions I'd like us to discuss and answer:
- What would we ideally like to see out of the social media management (replies, campaigns, etc)?
- Can we, as a working group, provide the level of sustained contributions around this or should we seek a dedicated resource from the foundation?

**Comment by subfuzion** [comment]
@mikeal, this answer doesn't address all the points you raised (still mulling it over), but I thought you were doing a great job of handing the tweets on official_iojs. I'm generally pretty amazed by your ability to adeptly handle the volume of communication you do. Have you considered sharing that burden with a few of us on the evangelism WG? Perhaps on some kind of rotation so we don't step on each other's toes? Perhaps you only tap one or two of us when you know you'll be busy.

**Comment by subfuzion** [comment]
The general level of communication and activity has gone way down recently. I do feel this partly due to a feeling of being in a sort of limbo while you and other leaders have navigated the reconciliation process. The last conference call we were going to have as the Evangelism WG on July 1 was canceled and not rescheduled (that I was aware of, although I might have missed due to a very intense work schedule the past few weeks).

**Comment by subfuzion** [comment]
Also, at some point I had noticed that you were unsubscribed from the Evangelism gitter room and not responding to mentions. I figure you need to do what you can to improve the signal-to-noise in your life, but as conduit to the rest of the leadership and ongoing reconciliation process, perhaps we can at least have a monthly working group meeting with you for discussion and planning purposes and bring us up to speed on various issues, such as the ongoing release process proposal. None of us are as connected to what's going on as you, so to some extent, answering the questions you raised -- and channeling our collective energy -- needs some input and guidance from you. It takes a great deal of energy to keep abreast of things the way you do, and we're fortunate in the community to have you. I really appreciate that you're asking what we think about the questions you raised, but I also am very interested in hearing what _you_ think simply because I feel you've got the best vantage point right now.

**Comment by rvagg** [comment]
It'd be great to find a way to do this from within this WG rather than getting Foundation resources for it.

Maybe we can get a group of people in this WG to come up with a schedule for monitoring and maintaining the Twitter handles? It's probably not a single-person role because it can get old really quickly (speaking from experience). Maybe it could be done on a weekly basis?

**Comment by danielkhan** [comment]
Although we'll need a discussion about exact tasks, procedures and communication channels I can offer some of my time if you need help.
I got the official approval that I can spend some of my working hours for Node.js contributions. (I'll spend it with documentation for now). We have a Buffer account and several monitoring tools in place and  I could cover the EMEA time zones at least.

**Comment by mikeal** [comment]
One of the challenges here, and I'm not trying to push us in one direction or another, is that this will require a more sustained effort on the part of the contributors than many of the other tasks we have taken on so far. We've had a lot of amazing success optimizing for "opportunistic development" (tasks people pick up when they are interested when they happen to have time) but this is quite different.

I'd like to hear suggestions for how we can split this up but first I think we need to answer the first question which sets some goals about how good we want this to be and some of the things we want to accomplish with social media.

> Maybe we can get a group of people in this WG to come up with a schedule for monitoring and maintaining the Twitter handles? It's probably not a single-person role because it can get old really quickly (speaking from experience). Maybe it could be done on a weekly basis?

That could work. I think setting a "check in" schedule (30 minutes every 4 hours) could also work. That's long enough to build up a queue of things to respond to.

Also, if we're running a campaign we can queue everything up ahead of time in bufferapp and bufferapp has some really good tools for sharing access as well.

**Comment by bnb** [comment]
Have any decisions been made on this?

**Comment by bnb** [comment]
Closing, as discussion has halted. Feel free to re-open if the issue needs to be discussed further.
