### ISSUE TITLE
Meetup "starter kit"

### ISSUE THREAD

**Issue by mikeal** [nodejs/evangelism#162]
It would be great if we could put together a resource for the website that helped people start local meetups about Node.js.

Thoughts?

**Comment by mikeal** [comment]
Additionally, we should create a directory of local meetups the same way we have one for NodeSchool events.

**Comment by Trott** [comment]
The page could have some standard info and then a link to a Wiki page attached to the repo. We could invite the organizers of existing Node meetups to edit the Wiki page, hopefully resulting in a document that is more dynamic and up-to-date than if it had to be part of the website.

**Comment by JungMinu** [comment]
+1 :smile:

**Comment by bnb** [comment]
I can work on this. Can everybody give feedback as to what you want included in it? Do we want a repo for it, or should it live here?

**Comment by mikeal** [comment]
I think it should be a new page under "Get Involved" and linked to at the top of that pages main content.

**Comment by bnb** [comment]
Oops - assigned bnoordhuis via misclick. My bad. I'll start on this.

**Comment by mikeal** [comment]
For reference, here's a pretty great guide by Brooklyn JS 
- https://github.com/knode/meetups/blob/master/brooklyn-ny-usa/brooklynjs.md
- https://github.com/brooklynjs/brooklynjs.github.io/commits/master

We may also want to consider some kind of "speaker index" to help people fine good speakers.

**Comment by bnb** [comment]
Also, this seems to be pretty good: https://github.com/nodeschool/organizers/wiki

**Comment by mikeal** [comment]
@bnb that's specific to NodeSchool, which are workshops, so some of it isn't portable. _But_ the things that are portable we should definitely grab because NodeSchool is wildly successful.

**Comment by bnb** [comment]
@mikeal Is there already a set of specific information that would go into this, or are we creating it from scratch?

**Comment by mikeal** [comment]
I don't know of a good guide yet. I know of guides for workshops and conferences that we can use for inspiration but a guide for regular meetups doesn't exist AFAIK.

I'll ask on twitter though to see if anyone has something to share.

**Comment by bnb** [comment]
I guess there are a few bits of information that I need to know to actually start pumping out the content of this:
- **Structure/format**: Will the meetups have a presentation, be hack-togethers, be networking events, be teaching events, or something else? Any and all of these can be correct, I just need to know which ones would be ideal and I would love to know of other ideas anyone has.
- **RSVP**: I don't think we will have a set number of seats, but should people RSVP over Twitter, GitHub, etc.?
- **Meetup sponsors**: Is this a thing we'll have? Event-by-event, long-term, or...?
- **Preparation and setup**: What needs to be done to get a location, schedule a date, resolve material needs, etc.?
- **Resources**: A list of resources that can be accessed quickly to answer both code-related questions as well as event-related questions.
- **Others**?

**Comment by Trott** [comment]
Maybe we can ping people who have actually run meetups and see if they can give their perspective on @bnb's questions, etc.? I still suspect setting up a wiki page for them to edit might be a better way to generate content from them than a back-and-forth in this issue, but what the hey, here, I'll ping some folks. @dshaw @paulgrock @visnup @emilyrose @tonypujals

**Comment by mikeal** [comment]
Also @jed @brianloveswords @kosamari from BrooklynJS

**Comment by bnb** [comment]
Would it be a good idea to put a tweet out from the official Node.js Twitter requesting any and all meetup organizers to comment here with their points?

/cc @mikeal

**Comment by paulgrock** [comment]
A little context, I help run [SFNode](http://www.meetup.com/sfnode) and below is how we handle our events. 
- **Structure/format**:  2 presenters from across the community give a 20-30 minute talk about a topic that is relevant to Node in some way. We generally have one beginner type talk and a more advanced one. Structuring our events this way allows us to reach a wide audience and have something more in depth for those that have been in the ecosystem for a while. We consistently have our events on the first Thursday of each month which I think really helps our attendees plan ahead. For instance if someone wants to speak at one of our events but can't make it to the next one it's easy enough for us to slot them in a few months in advance.
- **RSVP**: We base the number of RSVPs depending on the capacity of the space we're using for the month. For the most part we aim to have 70-100 people attend. We use meetup.com because of it's popularity, reach and ability to manage our guest list.
- **Meetup sponsors**: No sponsors for our group. Though we do have a company around SF host the event which usually involves setting up places for guests to sit, providing food/drinks and A/V setup for the speakers. 
- **Preparation and setup**: For location we started out by hosting at locations that our organizers worked at or knew people who worked at that place. After a few months companies started reaching out to us to host. If we haven't had a company volunteer to host we can fallback to one of our organizers' locations. A lot of locations require a guest list for security purposes. Having a copy on hand is also good if the event is rigid about RSVPs and waitlists.
- **Resources**: I've got nothing for this one.
- **Others**? Something that has been really helpful for SFNode is having an organizing team of around 4. Having a small group of people allows organizers to not stress over missing an event if they are busy, traveling or anything else. It also makes it so one person isn't burdened with all of the organizational tasks. Having at least 2 organizers at each event is quite handy as well.

If I missed anything that people have questions about just let me know.

**Comment by bnb** [comment]
Thanks a ton, @paulgrock! That's exactly the type of information we're looking for.

A few questions: 
- Have you always had the two speaker meetups? If so, was this an arbitrary choice that worked well, or was there a specific reason behind it?
- Do you require all attendees to RSVP, or is there an allowance for people to just show up?

**Comment by paulgrock** [comment]
1. For the most part we've always had 2 speakers at our events. Once or twice we've had three people present but it's a bit of an aberration. The choice was made to go with 2 topics to keep the meetup short and not take up everyone's whole night.
2. We ask everyone to RSVP but aren't strict about checking at the door. Because 40-60% no show on their RSVP we tend to let most people that show up into the event.

**Comment by rosskukulinski** [comment]
I've been fairly impressed with the London Node User Group (https://github.com/lnug/) and node.dc (http://www.meetup.com/node-dc/).  cc: @iancrowther @orliesaurus @danmactough.  Maybe some of them would be willing to make suggestions.

**Comment by danmactough** [comment]
Speaking for Node.DC (and thanks, @rosskukulinski -- we miss you), the biggest challenges to keeping our meetups successful have been:

## Venue

Co-working spaces have been our go-to meetup venue hosts, but with attendance sometimes surpassing 100 people, it's a challenge to find a reliable, free venue. The company I work for, Social Tables, will be moving in December to new offices where we'll have event space -- that will solve the venue problem for us.

## Cadence

It's really helpful for your members to know when to expect your next meetup. We try to have our meetups on Thursdays (typically not the first Thursday of the month), and we try to have a formal meetup once a month. Sometimes we fail.

To your specific points:

## Structure/Format

We are continually experimenting with format. For a long time (before I was an organizer), the format was all lightning talks. Then we tried 2-3 20-minute talks. Both of those formats made it difficult to find enough presenters.

For the past year, we (mostly @adunkman) have been soliciting proposals for talks and planning meetups out a calendar quarter at a time. These talks have all been long-format (40-minute) talks, and they've been really successful.

### Informal Meetups

The best thing we do as a meetup, though, IMO is our Node Nights (credit @joshfinnie). We plan these in between the formal-talk-style meetups (2 weeks in between), and sometimes host them in DC with NodeDC, and sometimes host in Arlington with Nova Node (cc @danpaz).

A Node Night is part "Learn You Node" NodeSchool and part hack night. We hang out, socialize, hack on some code, help newcomers learn node. It's been incredibly effective in building our community.

The only problem we've had is that publicizing them is difficult. They're not "Hack Nights," so when we called them that, we didn't get the event we were looking for. They're not really NodeSchool (to the extent people know what that is), so that's not great. No one knows what a "Node Night" is.

Anyway, we're still working on it. :smile: 

## RSVP

We use meetup.com to manage RSVPs so we can limit attendance to the venue capacity and plan food/beverage. We typically see ~50% of RSVPs actually attend.

## Meetup sponsors

The company I work for, Social Tables, is a sponsor of our group. That means we buy food/bev. As I mentioned above, we will also be providing a standing venue soon.

Harvest is also a sponsor -- they pay our Meetup.com dues.

My previous company, Terra Eclipse, was also a sponsor -- we provided free venue space.

We have occasionally held sponsored meetups. Strongloop (@jakerella) gave a nice talk a few months ago. Other sponsored talks we've had have been pretty meh -- mainly recruiting events.

## Preparation and Setup

I mentioned the difficulty with venue already. The other logistics will vary greatly.
- at some venues, we need to bring signage
- at one venue, we need someone to man the entry from the street because the building is locked 
- getting the food and beverage to the venue -- pay for Drizzly
- do you need to clean up
- what are you going to do with leftovers
- where can you go afterwards for drink and more conversation

## Resources

Not sure what you're looking for here.

## Others

Be prepared to enforce your Code of Conduct. We had one event about 1-1/2 years ago where the speaker, completely out of the blue, made a really inappropriate joke during his talk. Then another. And finally one more. Thankfully that was all because none of us were ready to step in, and we ended up letting it slide without saying a word.

We really dropped the ball, and I will never let that happen again.

## 

Hope that helps.

**Comment by iancrowther** [comment]
Hey all,

Here is an overview of the London Node User Group (LNUG)

# Structure

We run x3 20 minute talks with 10 mins for Q&A.  
We try to put on themed nights such as IoT, performance, testing but this takes a LOT of work to approach speakers and maybe a bit beyond beginner.
We also run a segment called Community Announcements which is great as its very interactive with the audience.  It runs as follows:
- We get job seekers on the mic to intro themselves
- We get employers on the mic to highlight their openings
- We offer the chance for people to ask for help with projects, get feedback, advise or whatever
- We give out the news such as node releases, any government legislations which may have an impact to contractors, any security issues etc.. just the news!

Getting the audience on the mic makes networking super easy and ensures people know who to speak to and don't miss out.  Everyone has had a few beers by then so its a lot of fun, some heckling and general mayhem.  As a host, this is my favourite part of the event as I honestly have no ideas whats coming.  Also it cuts out recruiters and avoids job board spam.

# RSVP

We use ti.to for the main tickets (currently at 130 due to venue capacity, we used to fill 200)
We do a few things here, we have provided block tickets to some code academies meaning they just have 10 tickets a month to distribute as they wish.  Its keeps the door open to new attendees from new semesters etc.  These targeted block ticket allocations allow us to shape the audience and keep it a mix of beginner through to advanced and allows us to be a very diverse crowd.. not just the developer stereotype.
We also have tickets for waiting lists etc so its easy for us to promote latecomers :-)
Everyone has to have a ticket including organisers & speakers, this is so we know how much food to order.

# Sponsors

This is important for us:
- Doorman / Security 
- Video Recording
- Beer
- Pizza
- Swag

Currently we offer a standard sponsor pack, paid in advance, invoiced from LNUG directly.  We are in the process of establishing a tiered sponsorship plan so we can cater for companies of all sizes and take on some longer term partners.

It is extremely important for us to try and select local business over established brands and chain suppliers.  For instance food is provided by a local cafe over subway (same price per head).

# Preparation:

Blimey! We try to get venues for 6 month blocks!  We have a google calendar to try and be consistent with things that need to be done in preparation (with varying success!).  You need hosting slides, to test the A/V, allow speakers to test before the event starts etc.

There are now 17 people who help organise LNUG and each one is delegated a task.  Each delegated task has a todo guide, for example how to write the newsletter.  These guides, outline what key info needs to be included, what services to use and when to ship.  Each organiser completely owns their task and is responsible for it.  Each task is meant to have a shadow owner in case the main owner is on holiday or sick. the guide is meant to make a handover simple.  This helped to decentralise the org and we can painlessly absorb people coming and going.

Signage is a good shout!

We have x2 pizza runs.  the first one is early and gets devoured! the second one means late comers don't miss out and everyone is supplied with a supply of warm pizza and cold beer!  We get good feedback for this.

If you supply drinks etc, get them delivered! the additional cost is worth it as you have too much else going on and need to be onsite.

Always thanks everyone who has been involved! from putting out chairs to a major PR.

Make sure everyone knows where to find links (gitter room & twitter), knows when the next event is and where.

Make sure the address is on tickets, the website, the newsletter.. basically everywhere.. and be clear on how to cancel them.

# Resources

We have an event planning repo which is private.  we could mirror this and add some sample docs

# Other

Yep code of conduct! We have an attendee blacklist.

Phew, hope that helps.. Ive skipped over lots tbh but this thread will evolve for sure

oh! and we should have an organisers chatroom for pointers such as hosting tips (how to quieten a chatty room or how to filler whilst a speaker setups up)

**Comment by bnb** [comment]
@iancrowther @danmactough Just wanted to express my gratitude for your awesome notes about your meetups. You guys do an awesome job with your events, and I appreciate you sharing your experience with us.

Working on compiling everybody's notes into an outline now.

**Comment by rosskukulinski** [comment]
I'd also like to chime in that we should include a recommendation to share the workload.  Running a successful ongoing meetup/event requires significant (and sometimes thankless) work.  LNUG, node.dc, and SFNode have done well to utilize several organizers to not over-load any one individual.

Something I've learned the hard-way organizing BayNode is that burn-out is a very real threat to the people running meetups.  I don't mean to discourage people from trying to organize events -- but rather to encourage them to find other like-minded people to work with.

**Comment by orliesaurus** [comment]
In addition to what the legendary @iancrowther said: 
- We have a code of conduct and we mention (the redux version) at the start of every meetup.
- We semi-manually update the site a few weeks in advance of a meetup
- We always welcome people to give us feedback: we mostly use Github and we set up a repo to handle that part but also have an open email for all more private feedback (ex. if harassment happens?) and ofc. on sight organisers are always happy to help
- We manage the speakers on GitHub so its super transparent and everyone knows who will be speaking next
- We send out a newsletter every month a week or few days before the event with the talk titles, avatars, twitters(or simil) of speakers and links to our community github repo (feedback/request for new speakers)
-  We have a team of 10 people helping with the meetup and one or two "overseers" that have been in the community long enough to understand, appreciate and drive the meetup direction 
- We always ask for volunteers to help, anyone is welcome to join the "organisers-team"
- We don't talk about Java. Ever.

As I am now no longer in London :'( , I'm happy to help new chapters of the "Your City Node User Group" to get started - just ping me on Gitter - https://gitter.im/lnug/discuss

**Comment by jakerella** [comment]
@mikeal @bnb As you start getting this guide together, make sure there are two sides: people looking to start/host events, and companies looking to help. I'm envisioning a sub-site with resources for organizers, including a way to "match up" usergroups with sponsors and even venues.

I'm happy to help work on that, and as a side note, StrongLoop (and now IBM) is willing to help sponsor some of these new groups!!

**Comment by mikeal** [comment]
@jakerella we can work towards that but we should keep it simple at first.

**Comment by iancrowther** [comment]
lol - "We don't talk about Java. Ever" - I remeber that guy!!

**Comment by iancrowther** [comment]
@bnb - welcome.. every little helps :-)

**Comment by kosamari** [comment]
@bnb @mikeal 
At BrooklynJS, we don't have starter kit but have quite a bit of documentation on our repo
- [monthly TODO](https://github.com/brooklynjs/brooklynjs.github.io/blob/master/monthly-todo.md) list to prep for meetup 
- [Speaker FAQ](https://github.com/brooklynjs/brooklynjs.github.io/blob/master/speakers.md)
- [Attendee FAQ](https://github.com/brooklynjs/brooklynjs.github.io/blob/master/attendee-faq.md)
- [our Budget](https://github.com/brooklynjs/brooklynjs.github.io/blob/master/budget.js)
- [sponsor page](http://brooklynjs.com/sponsorship.html)

Other advice would be
- **have co-orgnizers** can't stress this enough
- have set schedule (we are always 3rd Thursdays)
- (if possible) have set location

**Comment by kosamari** [comment]
Also waffle.js folks just started their meetup 3 months ago so they might have fresh perspective on how to start.

**Comment by ahdinosaur** [comment]
i organize [NodeSchool Wellington](http://nodeschool.io/wellington), here's my story:
- **Structure/format**: our meetup happens every Tuesday evening at 6:30pm at [the same location](http://devacademy.co.nz/). the format is we all hang out together in a room with a bunch of tables (usually we arrange the tables so we all face each other). everyone works independently towards their own personal goals, people talk amongst themselves and even people who don't know much javascript are able to help direct newbies in the right direction. a few of us hold the space and ensure nobody is lost or blocked. the _only structure_ is a check-in circle ~30 minutes in where we all answer: "what's your name?", "how are you feeling today?", "what are you offering to / requesting from the group?", this lack of structure is intentional.
- **RSVP**: we use [Meetup](http://www.meetup.com/Enspiral-Dev-Academy-Meetup/).
- **Meetup sponsors**: i can't be bothered to find sponsors, nor do i think it always adds value to a meetup, instead our attendees bring food to share with each other.
- **Preparation and setup**: find a location, pick a day, post an weekly recurring event that people can RSVP to, arrive > 15min before the event time to post a sign outside (with your phone number) and setup the space, ensure adequate table and power capacity, let people inside the space as they arrive, introduce yourself to any newbies, open the check-in circle ~30 minutes after the scheduled start, let people know who is available to help as a mentor, find a co-organizer.
- **Resources**: we use our [GitHub repo](https://github.com/nodeschool/wellington) for this.
- **Others?**: focus on building a thriving community with healthy culture and sustained energy, in my opinion a meetup should be a safe space for people to spend their evenings with others while making progress towards their personal goals. personally i don't care for the typical meetup format of monthly talks, which is why i started a meetup with a different format.

**Comment by bnb** [comment]
I'm having a hard time consolidating all the information in this issue without giving every example that people have provided, long-form. Do the people who have contributed to this thread (and WG members) feel that giving a general overview of each topic and bullets with summations individuals' stories would be appropriate? I want to include all the great information posted here, but there's so much, in such detail, that it's extremely hard.

**Comment by Trott** [comment]
@bnb I think that sort of information totally makes sense, but that it should be a wiki page so other people can contribute easily. The website doc should contain a basic overview: 
- what type of information is this and who is it for? 
- general encouragement for anyone so motivated to start a meetup or whatever
- _maybe_ a highlight or two from the doc
- and, of course, a link to the wiki doc

**Comment by Trott** [comment]
Continuing the thought...once there's a big messy awesome wiki doc in place, then we can start adding things to the website doc to make it a real-ish starter kit. I'm not sure what that would be, but maybe there are forms or organizing tools or checklists that can live there.

**Comment by mikeal** [comment]
Please don't use the wiki, just commit a markdown file.

**Comment by bnb** [comment]
@mikeal Yes, I know. I'll be submitting a Markdown file here, and then pulling that into the nodejs/website repo under the Contribute template.

**Comment by bnb** [comment]
Just an update, I've got a good structure down now, and am on the final step of pulling content from people's feedback here into the doc - shouldn't take an extraordinary amount of time. Expect a PR by Monday, but probably sooner.

**Comment by mikeal** [comment]
Just ran across this which is quite nice http://hood.ie/contribute/#talks

**Comment by iancrowther** [comment]
nice.. that'd be really handy!

**Comment by visnup** [comment]
coming to this pretty late. some personal viewpoints from co-organizing wafflejs:

## manifesto

I encourage organizers to write out a manifesto of what values they want to deliver on in a meetup. I wasn't interested in starting one until I went to brooklyn_js and saw that a meetup could do lots of _other_ things. wafflejs was a reaction to the startup/corporate-style meetups in the bay area: clean, paid-for/entitled, technocratic/exclusive, singularly tech-focused. I try to steer wafflejs to be: eclectic, you pay for value, inclusive, everyone-has-a-hobby-focused (the other organizers might have slightly different motivations).

## repetition

venue, cadence, _inspiration_ don't change every month. we're always in the same place (soma streatfood park), the first wednesday of the month, rain or shine. this lets attendees plan ahead and also allows us to plan speakers in advance pretty well too (oh, can't talk Dec 2? how about Jan 6?). taking as many things off of your plate to do every month, means you're more likely to succeed at doing it every month.

## structure/format

we do 4x lightning talks. we're open to experimentation on number and length, but shorter and more has given us the bonus of more variety and speaker promotion/outreach. having 4x speakers tweet to their followers gets more attendees than 2x speakers doing the same. to help facilitate the shorter talks, we advise attendees to ask questions to the speaker directly, face-to-face, and try to formalize their introduction (removing the speaker intro and Q&A slides).

## RSVP

we dislike meetup.com. we charge $10/$12 per ticket and include a waffle. this and (what I'm hoping is) high-quality keeps us at an 80% attendance rate. ti.to has made several things easier and they're very responsive to feedback. we've found that meetup.com attendees expect too much free 💩 and don't show up (at least in SF).

## sponsors

our work has been very generous and sponsored every one so far. we've started finally getting consistent and growing outside sponsors too. sponsorship money has bolstered ticket sales to cover the cost of the venue and stickers and our growing stockpile of A/V equipment. in the future, sponsor money will be used to just make things better for attendees and increase the value of their ticket, like a food voucher (our venue is a food truck park). we'll likely never buy attendees alcohol.

## budget

I think a working budget example is key for anyone trying to start a new meetup. it very quickly answers the questions of should or how much I can expect to pay for things. we publish our budget for attendees and other organizers to reference. we stole this from brooklyn_js.

## preparation

we have week by week checklists which we work through mostly like clockwork every month. we have a weekly sync meeting to go over the checklists and make sure people know what we still need to do (get 2 more speakers; re-order stickers; figure out how to get more students).

## resources

we've been slowly amassing a huge A/V setup. some stuff is still borrowed from @mikeal. our venue doesn't have a very good A/V setup so we've had to build our own. this was a trade-off based on what we wanted out of our venue (not corporate, not a bar, not _clean_). we have 3-4 organizers and lots of friends. getting at least one co-organizer to begin with is key.

## feedback & iteration

we send out a survey asking explicitly for negative feedback afterwards. twitter fills up with lots of positive encouragement which is great, but to improve we need to know what went wrong. sometimes it's things we already know (audio was borked), sometimes it's stuff we hadn't considered before (want more socialization time), sometimes it's stuff we disagree with (don't like karaoke). but we try to empathize with all of it and try to figure out how to address it. we hold a retro meeting/sync the next day to go over our own lists of things we want to fix/improve and come up with some solutions. that's not to say we solve them immediately, but we keep trying.

## charity

also stolen from brooklyn_js, we donate any remaining profit every month to a local charity. sometimes it's $0.05. sometimes isn't $200. it keeps us honest about what we use the money for since anything we buy is basically taking money away from charity for us. this is another reason I don't feel compelled to buy someone a $4 beer vs. giving that $4 to charity.

## links
- [our budget](https://docs.google.com/spreadsheets/d/1D3_RS7sMBZZxJRSmrTM_3Rf0ZyTfD3ApbftW8TwZ468/edit?usp=sharing)
- [speaker info](https://wafflejs.com/speakers)
- [sponsor info](https://wafflejs.com/sponsorship)

**Comment by danmactough** [comment]
@visnup That's great stuff. We've thought about moving to a paid model (at least for certain events), knowing that it helps prevents no-shows. FWIW, we've generally decided that it presents enough of a barrier to newcomers that it's not worth the trade-off.

**Comment by visnup** [comment]
@danmactough good point. on the other end of the spectrum, we have a student sponsor ticket for 2x the regular price, which goes directly into free tickets we have for students. increasing student/newcomer attendance has been an issue which has come up in our retros. the best solution we think (which we haven't accomplished) is to get student speakers. they will naturally bring in their own network of people and it can grow by word of mouth from there (assuming we deliver on providing a novel/good experience).

**Comment by danmactough** [comment]
I love that student sponsor ticket idea @visnup 👏

**Comment by PatrickHeneise** [comment]
we're putting together a metalsmith build and event management system for meetups called `gitevents`. The BarcelonaJS.org site is already running on it. https://github.com/GitEvents/core contributions highly welcome!

**Comment by eudaimos** [comment]
@mikeal @bnb Should this issue be closed?

It's a year old and we have the [Meetup Starter Kit](../blob/master/documents/meetup-starter-kit.md)

Is there more that needs to be done?
Might we open a new Issue to capture feedback from organizers once we've completed the audit?

**Comment by bnb** [comment]
For a round of evaluation on the Meetup Starter Kit (what's been successful, what's not been as successful, and what we can do to improve) check out #257!
