### ISSUE TITLE
nodejs/jobs Community Repo

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#176]
I was brainstorming ideas that we can use to reach a wider Node.js audience, during which I was reminded of job boards and GitHub at the same time. This sparked an idea: Create a GitHub repo called nodejs/jobs. 

In this repo, companies can add job listings as issues, and Node.js workers can add themselves as candidates as issues. There would be a tag for each side, `looking for person` and `looking for job`. We could link this from the top-level navigation on nodejs.org, which would hopefully drive a lot of traffic.

I would be willing to write all the necessary documentation for this repo, assuming it is put under the control of @nodejs/evangelism and it adopts the standard models that are applied to all the Node repos, a la io.js.

We could publicize this, maybe create a Twitter account and set up IFTTT to publish new issues, and spread the word as far as possible. If done correctly, it could be a boon for both companies and employees.

Thoughts?

**Comment by rvagg** [comment]
thar be dragons this way

It's going to need heavy-handed moderation as recruiters are _very_ hungry people and will try hard to get their word out even if they find a forum that's only vaguely related to the job they are trying to fill. I can see this getting messy very quickly and might not be something that we want to drain our resources trying to keep sane. -0 from me.

**Comment by bnb** [comment]
@rvagg Is there a way to mitigate that problem? Or is there an alternative that we can implement? One reason I thought of this was because of this comment: https://github.com/nodejs/evangelism/issues/162#issuecomment-145829320. I think that having some sort of forum for this type of thing is something that could be successful and beneficial for the community, and is worth investing our time in figuring out.

**Comment by mikeal** [comment]
I'm going to echo @rvagg's concerns. If you look at what the Lever jobs board has (which is still forwarded from http://jobs.nodejs.org ) there's 8K posts, and that's with people paying something like $350 per post per **month**. We don't have the resources to manage that many posts, and you'd expect double that if it were free, maybe more.

Additionally, treating this as a community resource means that we open it up to some level of community standards. It's only natural that a community working to maintain such a resource would want to have some level of control over what their effort is being used for. This opens us up to a very long and endless bikeshed about what those standards are that will inevitably burn out the people who were working on this resource.

As an alternative, the foundation is considering a small job board as a corporate member benefit. That would limit the number of posters and, since the foundation has member services resources, is something they could maintain with a minimal amount of work.

**Comment by bnb** [comment]
@mikeal I see. Well, the solution you mentioned is reasonable. I'm still interested in figuring out a way to promote community members of non-guru skill level looking for Node.js jobs - if anyone has further ideas for that, I'd really like to hear them.
