### ISSUE TITLE
Help with V2 of the presentation: The Enterprise Case for Node.js

### ISSUE THREAD

**Issue by gtewallace** [nodejs/evangelism#239]
As @vdeturckheim posted in #217 , many Node.js users have requested a presentation that consolidates all the best stats and thinking on why enterprises should consider Node.js for their systems of engagement.

The Node.js Foundation has worked with members and the community to develop V1, which you'll find here https://nodejs.org/en/foundation/case-studies/#presentation-the-enterprise-case-for-node-js

As we work to update and improve this deck, please use this issue to provide thoughts. Specifically, are there sections you think the presentation is lacking? (E.g. we are thinking of including a section called "Node.js and the Developer Experience.") How can the existing sections be improved? What new use cases or data can we include?

Thank you!

**Comment by vdeturckheim** [comment]
Here are the first remarks I have on this v1:
This is a very good document:
- it focuses on issues enterprises care about (for instance: perf, dev happyness (or at least eas of hire))
- it pictures success stories from well-known players
- it shows the maturity of the node environment

The improvement I would see after a first read:
- It has too much verbosity in some slides: if you have to present it, people will read the slide and not listen to the presenter (e.g. slides 9 16 17)
- Slide 9, have the enterprises pictured here been chosen since they are member of the Foundation ? I feel it misses some players (like Keymetrics for instance). It might create an unfair endorsement from the Foundation.
- More generally, we might want to provide this presentations with speaker's note. Use of them will be optional but very useful to help some people.
- I would put more effort in stating that the Node Foundation is vendor neutral and therefore using Node is safe competitively speaking.

Regarding the overall strategy: I believe providing a set of medium-sized presentation is better than just a massive one (In this idea, "Node.js and the Developer Experience." should be another presentation.). The interest I see here are:
-  If you have a set of short (10min max presentation), you can better manage the timing of your interventions (there is nothing worst than a speaker skipping slides because he has to hurry).
- Audience's interest can be regained at each new document.
- You get a set of small conferences you can place in a cycle (for instance, one at each Monday lunch for a month). I know a lot of enterprises who love such a format.

So, of courses, this is only my opinion and is based on the small experience I have. I am certain a lot of people have much to say on this topic and am really excited to read it !  

Thanks for reading !

**Comment by vdeturckheim** [comment]
@gtewallace should we start iterating over a v2 version with collaborative tools ? (google slides / markdown doc and PR / anthing else ? )

**Comment by gtewallace** [comment]
awesome! thank you - I love the suggestions - yes let's do that. Here's a Google Slides version.

https://docs.google.com/presentation/d/1KdYniohBE_APp8ngD_TTE0-Hl5loxXCTnj1AnEorebc/edit?usp=sharing

**Comment by bnb** [comment]
Just wanted to drop a line and say that we're going to try to get more eyes and voices into this - it has been posted through the Node.js Medium blog: 

https://medium.com/@nodejs/version-1-of-the-enterprise-case-for-node-js-presentation-424553a383dd#.4n43zvwm9

👍

**Comment by gtewallace** [comment]
@bnb what are your thoughts for next steps? would love to get work started soon. lmk if you'd prefer for me to take point.

**Comment by vdeturckheim** [comment]
@gtewallace Sorry I got super busy last weeks. It should get better now. I am still willing to work on that however !

**Comment by gtewallace** [comment]
no worries - I wonder if a hangout would be a good next step - anyone interested in contributing can join and we can decide on what we want v2 to look like and start a plan to get it there.

**Comment by rosskukulinski** [comment]
I'm coming in very late to the party!  I've been on a few calls with Mikeal with Analysts essentially pitching a variation of this deck.

What timezones are people in ( @gtewallace @vdeturckheim @bnb )?  I agree with @gtewallace in that having a 30-minute hangout to kick the process off would be good.

**Comment by gtewallace** [comment]
thanks @rosskukulinski 
I am us Eastern

**Comment by vdeturckheim** [comment]
@gtewallace yes, a hangout kick-off would be a good idea.
@rosskukulinski I'm in Paris, I do not mind having a call late (midnight UTC +/- 1h)

**Comment by danielkhan** [comment]
I'm interested to listen in.

**Comment by bnb** [comment]
✋ Also up for it! I'm EST, but can/will do any time. I'd throw together a Doodle, but every time I try to set one up correctly I fail miserably.

**Comment by vdeturckheim** [comment]
@bnb I was about to create a Doodle but got lost with the Timezone stuff.
I am available every evening next week except on Wednesday.
Evening in Paris means:
Paris: 7PM -> 11:59PM
New York: 1 PM -> 6PM
What about:
-> Tuesday OR Thursday at 2PM (New York time whatever that means) ?

Ping @gtewallace @rosskukulinski @danielkhan
Should we ping Mikeal here ?

**Comment by bnb** [comment]
@vdeturckheim I can do anytime 1-6PM EST (which is New York time), any day. Tuesday at 2PM EST works fine for me - Thursday at 2PM EST probably won't work for @rosskukulinski and I because of a weekly meeting conflict from 2-2:30.

**Comment by gtewallace** [comment]
Hi all. This week may be hard for me as i am at a conference. But please proceed. Mikeal is aware of this thread, but def bring him in if you want.

For me, some of the questions we should ask at the first call are:

Should we make the preso modular?

Are there other sections we should add?

What can we do to improve the current sections?

Thanks again everyone.

Greg

**Comment by vdeturckheim** [comment]
@bnb It will be complicated for me tonight. Let's postpone to next week: I have nothing planned yet.
@rosskukulinski @gtewallace @bnb -> what would be the best day for you all ? I should be available every evening.

**Comment by bnb** [comment]
@gtewallace Wanted to ask if this was resolved, and if it needed any further work? Not sure what the status is otherwise.
