### ISSUE TITLE
Evangelism WG Effort Kickstart: Quick Summary Articles of Core/WG Issue Threads

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#241]
@trevnorris recently [asked on Twitter](https://twitter.com/trevnorris/status/774001582635569152) if the Foundation would be able to hire a writer to summarize threads that run longer than would be easy to read in a timely manner for full comprehension. I assume this would apply to Core and other supporting WGs.

Here's a rough draft of things that _I_ think would need to be addressed - **absolutely** want feedback from both those who are participating in these threads and those who would be reading the summaries on what the best way to do this is.
# Initial Quick Summary Article questions and criteria for developing a sustainable process:
- How do we present these articles? For example, are they in the style of a small blog post, a list-style post of the most important and relevant comments?
- How do we become alerted of a thread that needs summary? For example, when someone mentions @nodejs/evangelism with a request in the thread, when someone creates an issue here, or via some other method of communication?
- At what point in a thread should a summary be needed? Should the summary begin when a decision is made, when discussion is completely finished, or at some other point - such as on a case-by-case basis?

//cc @jasnell @dshaw

**Comment by vdeturckheim** [comment]
the idea is pretty good !
- If a non finished thread get summarized (according to the strategy chosen), is it locked and continued somewhere else ?
- If not, will the article be kept up-to-date or does it represents the threads a a given time ? (Implying that more than one articles can be written on the same thread)

Summoning the WG in the thread seems a good idea. Also, it would be sometimes useful if one of the thread participants could join the article writing process.

I think threads probably do not need to be finished to be summarized. If a thread is asleep for a while, it might be a good time to summarize it in order to make the wake up easier.

**Comment by bnb** [comment]
@vdeturckheim Good questions! I think we need to rope in someone commentary and feedback from @nodejs/ctc on this to make it effective for their needs.

> Also, it would be sometimes useful if one of the thread participants could join the article writing process.

That is definitely a 👍 from me. Always helps to get someone who is well-aware to clarify and help write - even if they're just talking with the writer about the content.

**Comment by vdeturckheim** [comment]
@bnb any roadmap for those ?

**Comment by bnb** [comment]
@vdeturckheim Not yet. Very much want to get this up and running, but I haven't had enough cycles to do it myself recently. That should be changing shortly. 

It would be _awesome_ to get a PR with a start on a roadmap, if you (or anyone, of course) like to try to start that! 😊

**Comment by vdeturckheim** [comment]
@bnb Great, yes I was thinking of PRing that (I'm at the end of a cycle and have more time)

**Comment by bnb** [comment]
@vdeturckheim Would absolutely **LOVE** to see that as a PR! 👍
