### ISSUE TITLE
Podcast for Node.js

### ISSUE THREAD

**Issue by bnb** [nodejs/evangelism#259]
We discussed a podcast as a possible way to start working more with the community and messaging the difficult topics more broadly. 

- Driving toward community
  - Options
     - Focus on learning and sharing about meetups, WGs, and teams.
     - Working on driving vocal and simple solutions to broader issues that the community is having confusion or deep discussion about (LTS, buffers, etc.)

Ref: https://github.com/nodejs/evangelism/issues/250 /cc  @homosaur

**Comment by homosaur** [comment]
I'm going to do some research into the technical side of podcasting over the next few weeks. We need something that is portable, easy to use, using cheap or free tools, and doesn't have a single point of failure in regards to personnel, hosting or otherwise. Right now I am ONLY investigating technical things, but we can also discuss the format of the show in this thread. There were some good issues raised in #166 and a thread for possible guests in #204.

**Comment by Fishrock123** [comment]
I suspect a lot of the parts of streaming also carry over to podcasting to LMK if you want any help on that end.

Maybe we could use @mikeal's P2P voice call thing for this? It has recording capability I think. (And maybe even streaming capability?)

**Comment by mikeal** [comment]
I'll be working on a streaming solution this month as part of some work I'm doing for a live podcast I'm starting :)

**Comment by homosaur** [comment]
I would love to have a FLOSS solution for recording, even better if it's Node-y. It would be really awesome to send guests to a website rather than deal with the annoyance of Skype, Hangouts, etc, so Roll Call is definitely in my list of things to test.

I want to try out both post-recording compression as well as traditional mic-to-board and USB mic. I already know the former will yield worse results, but it's definitely possible that it will be good enough to use. I expect that to be the case actually.

If anyone has any softwares you'd like me to put in the testing stack, just let me know and I'll try to get it in.

**Comment by homosaur** [comment]
@vdeturckheim can you slap a "podcast" label on #166 and #204 as well? thanks

**Comment by vdeturckheim** [comment]
@homosaur done. good one :)

**Comment by rosskukulinski** [comment]
I think we should leverage [NodeUp](http://nodeup.com/) as our medium. @hackygolucky introduced @bnb and I to @floating who helps manage NodeUp (https://github.com/nodeup/contribute/issues).

NodeUp already has all of the infrastructure in place for creating and distributing the content, not to mention an extensive audience already.  Rather than having the "Node.js Foundation Podcast", I think we should collaborate with NodeUp to provide official content from the Node.js Foundation.  Co-branding & Co-marketing between Node.js Foundation & NodeUp is a win for everyone.

I propose post-holidays we schedule a hangout with the NodeUp folks to talk through what this partnership might look like.  I'm happy to take the lead on organizing that discussion with them.

**Comment by bnb** [comment]
@rosskukulinski Sounds good to me. Would very much like to include @homosaur in this Hangout, since he is very much leading this. I'd _like_ to set up a Doodle to help everyone schedule, but I can never do it right. 😅 Can someone help get a Doodle set up to pick a time for the hangout? Or, if the group interested in attending is small enough, do we want to just pick a day and time?

**Comment by homosaur** [comment]
@rosskukulinski @bnb 

Hey sorry y'all, I've been out of the loop for a bit with post holiday hangover and trying to fill in for vacationers at work. Totally happy to do a discussion on it. I think if we have existing people who can provide reach and expertise, that's a big win. Obviously NodeUp's folks are heavy Node contributors and it seems to be a big overlap in interest. The only trepidation that I've seen from past discussions (specifically #166) is that we have to be a bit careful on content if it's "official", but if it's a subset being curated for the purposes of the Foundation, I wouldn't see why that would be an issue. Probably out to ping @mikeal on this before we get too far down the road but I definitely think we should get some people together to start to discuss specifics as soon as possible.

**Comment by rosskukulinski** [comment]
Hi everyone,

Let's find some time to kick off the discussion later this week.  Here's a Doodle Poll - I'll close it Tuesday ~5pm ET.  http://doodle.com/poll/dwfghm3fy9xw8sq8

**Comment by bnb** [comment]
@rosskukulinski @homosaur @vdeturckheim  Let's try to sync up again. Apologies for missing the Doodle, @rosskukulinski 😞 - I need to find a way to actually get notified about GitHub things in a way that will work for me.

**Comment by rosskukulinski** [comment]
@bnb I'm going to have to step out of this conversation - I've got a bit too many things on my plate ATM.

**Comment by mikeal** [comment]
I know that several people have been working with NodeUp on getting different content into that feed including @rvagg who did a bunch of in-person interviews at NINA.

Whatever the scope ends up being for this podcast we can probably find a way to fit it into NodeUp. If you look through the history of the feed there are all kinds of different formats and you could easily distinguish what you're doing as some kind of "sub brand."

**Comment by hackygolucky** [comment]
Hey y'all, just poking this thread because I'd really love to see this happen. 

Do you think it'd help for us to list out some really great topics that could be featured, and then find folks who would be a great fit to speak to it?

**Comment by SarahKConway** [comment]
I think that's a great idea, Tracy. If you'd like I'd be happy to create a Google doc for us to track  topic and guest ideas. Might be easier to follow than a long thread here. @hackygolucky what do you think?

**Comment by bnb** [comment]
@SarahKConway Only concern with a Google Doc is discoverability - not extremely easy to discover and start contributing to a Google Doc. 

I think an easy win would to edit the original post with a link to a comment with @hackygolucky's list - that way, people can skip down directly to the list without _needing_ 100% of the context leading up to it 😁

**Comment by hackygolucky** [comment]
Hrm @bnb what list are you referring to? 

The problem with GitHub conversations is that they aren't great for everyone seeing all the input in one place unless we are asking for everyone to PR a list. 

For a quick 'everyone can chime in 'everyone, adding a link to a Google doc in this issue description as a call to action and then asking folks here to do that is a pretty speedy win.

**Comment by willprice17** [comment]
Sup

**Comment by bnb** [comment]
@hackygolucky Was referring to what you [said earlier](https://github.com/nodejs/evangelism/issues/259#issuecomment-297780672) about a list of topics - though I think you meant collectively, not sourced from you, which I misunderstood 😁

**Comment by bnb** [comment]
@hackygolucky / @SarahKConway wanted to check in and see what y'all thought of this. If we're still interested in moving forward, I definitely think this is a great resource. That said, the time and contributors are the blocker as far as I can tell - getting people to be able to do it is the hard part 😅
